apiVersion: skaffold/v3
kind: Config
metadata:
  name: fact-service
build:
  artifacts:
  - image: fact-service
    jib:
      project: org.skillsmapper:fact-service
manifests:
  rawYaml:
  - deployment.yaml
portForward:
- resourceType: service
  resourceName: fact-service
  port: 8080
